// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200616213449_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlphaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BandSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxCulmen")
                        .HasColumnType("float");

                    b.Property<double>("MaxTail")
                        .HasColumnType("float");

                    b.Property<double>("MaxWing")
                        .HasColumnType("float");

                    b.Property<double>("MinCulmen")
                        .HasColumnType("float");

                    b.Property<double>("MinTail")
                        .HasColumnType("float");

                    b.Property<double>("MinWing")
                        .HasColumnType("float");

                    b.Property<string>("SpeciesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            AlphaCode = "RWBL",
                            BandSize = "F-1A/M-2",
                            MaxCulmen = 16.5,
                            MaxTail = 105.0,
                            MaxWing = 135.0,
                            MinCulmen = 15.300000000000001,
                            MinTail = 64.0,
                            MinWing = 88.0,
                            SpeciesName = "Red-winged Blackbird"
                        },
                        new
                        {
                            SpeciesId = 2,
                            AlphaCode = "EABL",
                            BandSize = "1B-1",
                            MaxCulmen = 11.0,
                            MaxTail = 70.0,
                            MaxWing = 109.0,
                            MinCulmen = 7.0,
                            MinTail = 57.0,
                            MinWing = 91.0,
                            SpeciesName = "Eastern Bluebird"
                        },
                        new
                        {
                            SpeciesId = 3,
                            AlphaCode = "GRCA",
                            BandSize = "1A",
                            MaxCulmen = 17.800000000000001,
                            MaxTail = 104.0,
                            MaxWing = 99.0,
                            MinCulmen = 13.300000000000001,
                            MinTail = 81.0,
                            MinWing = 81.0,
                            SpeciesName = "Gray Catbird"
                        },
                        new
                        {
                            SpeciesId = 4,
                            AlphaCode = "BCCH",
                            BandSize = "0",
                            MaxCulmen = 10.5,
                            MaxTail = 72.0,
                            MaxWing = 73.0,
                            MinCulmen = 7.5999999999999996,
                            MinTail = 53.0,
                            MinWing = 57.0,
                            SpeciesName = "Black-capped Chickadee"
                        },
                        new
                        {
                            SpeciesId = 5,
                            AlphaCode = "BHCO",
                            BandSize = "F-1B/M-1A",
                            MaxCulmen = 16.0,
                            MaxTail = 79.0,
                            MaxWing = 104.0,
                            MinCulmen = 12.699999999999999,
                            MinTail = 57.0,
                            MinWing = 85.0,
                            SpeciesName = "Brown-headed Cowbird"
                        },
                        new
                        {
                            SpeciesId = 6,
                            AlphaCode = "BBCU",
                            BandSize = "2",
                            MaxCulmen = 23.899999999999999,
                            MaxTail = 167.0,
                            MaxWing = 147.0,
                            MinCulmen = 20.199999999999999,
                            MinTail = 146.0,
                            MinWing = 137.0,
                            SpeciesName = "Black-billed Cuckoo"
                        },
                        new
                        {
                            SpeciesId = 7,
                            AlphaCode = "BRCR",
                            BandSize = "0A-0",
                            MaxCulmen = 22.100000000000001,
                            MaxTail = 69.0,
                            MaxWing = 69.0,
                            MinCulmen = 16.899999999999999,
                            MinTail = 53.0,
                            MinWing = 57.0,
                            SpeciesName = "Brown Creeper"
                        },
                        new
                        {
                            SpeciesId = 8,
                            AlphaCode = "MYWA",
                            BandSize = "0",
                            MaxCulmen = 10.300000000000001,
                            MaxTail = 60.0,
                            MaxWing = 78.0,
                            MinCulmen = 8.4000000000000004,
                            MinTail = 53.0,
                            MinWing = 65.0,
                            SpeciesName = "Myrtle Warbler"
                        },
                        new
                        {
                            SpeciesId = 9,
                            AlphaCode = "MODO",
                            BandSize = "3A-3B",
                            MaxCulmen = 22.5,
                            MaxTail = 163.0,
                            MaxWing = 159.0,
                            MinCulmen = 18.0,
                            MinTail = 114.0,
                            MinWing = 131.0,
                            SpeciesName = "Mourning Dove"
                        },
                        new
                        {
                            SpeciesId = 10,
                            AlphaCode = "HOFI",
                            BandSize = "1B-1",
                            MaxCulmen = 12.0,
                            MaxTail = 66.0,
                            MaxWing = 83.0,
                            MinCulmen = 9.5,
                            MinTail = 51.0,
                            MinWing = 70.0,
                            SpeciesName = "House Finch"
                        },
                        new
                        {
                            SpeciesId = 11,
                            AlphaCode = "PUFI",
                            BandSize = "1-1B",
                            MaxCulmen = 12.0,
                            MaxTail = 87.0,
                            MaxWing = 87.0,
                            MinCulmen = 9.5,
                            MinTail = 53.0,
                            MinWing = 71.0,
                            SpeciesName = "Purple Finch"
                        },
                        new
                        {
                            SpeciesId = 12,
                            AlphaCode = "CSWA",
                            BandSize = "0A-0",
                            MaxCulmen = 9.9000000000000004,
                            MaxTail = 52.0,
                            MaxWing = 68.0,
                            MinCulmen = 9.4000000000000004,
                            MinTail = 42.0,
                            MinWing = 56.0,
                            SpeciesName = "Chestnut-sided Warbler"
                        },
                        new
                        {
                            SpeciesId = 13,
                            AlphaCode = "BGGN",
                            BandSize = "0A",
                            MaxCulmen = 11.199999999999999,
                            MaxTail = 55.0,
                            MaxWing = 56.0,
                            MinCulmen = 8.8000000000000007,
                            MinTail = 47.0,
                            MinWing = 46.0,
                            SpeciesName = "Blue-Gray Gnatcatcher"
                        },
                        new
                        {
                            SpeciesId = 14,
                            AlphaCode = "AMGO",
                            BandSize = "0",
                            MaxCulmen = 10.199999999999999,
                            MaxTail = 52.0,
                            MaxWing = 79.0,
                            MinCulmen = 8.9000000000000004,
                            MinTail = 39.0,
                            MinWing = 63.0,
                            SpeciesName = "American Goldfinch"
                        },
                        new
                        {
                            SpeciesId = 15,
                            AlphaCode = "COGR",
                            BandSize = "3-3B",
                            MaxCulmen = 24.0,
                            MaxTail = 148.0,
                            MaxWing = 150.0,
                            MinCulmen = 23.0,
                            MinTail = 97.0,
                            MinWing = 115.0,
                            SpeciesName = "Common Grackle"
                        },
                        new
                        {
                            SpeciesId = 16,
                            AlphaCode = "RBGR",
                            BandSize = "1A-2",
                            MaxCulmen = 18.199999999999999,
                            MaxTail = 79.0,
                            MaxWing = 110.0,
                            MinCulmen = 15.4,
                            MinTail = 66.0,
                            MinWing = 90.0,
                            SpeciesName = "Rose-breasted Grosbeak"
                        },
                        new
                        {
                            SpeciesId = 17,
                            AlphaCode = "BLJA",
                            BandSize = "2",
                            MaxCulmen = 25.399999999999999,
                            MaxTail = 148.0,
                            MaxWing = 148.0,
                            MinCulmen = 23.899999999999999,
                            MinTail = 106.0,
                            MinWing = 115.0,
                            SpeciesName = "Blue Jay"
                        },
                        new
                        {
                            SpeciesId = 18,
                            AlphaCode = "DEJU",
                            BandSize = "0-1",
                            MaxCulmen = 14.9,
                            MaxTail = 74.0,
                            MaxWing = 83.0,
                            MinCulmen = 13.9,
                            MinTail = 62.0,
                            MinWing = 72.0,
                            SpeciesName = "Dark-eyed Junco"
                        },
                        new
                        {
                            SpeciesId = 19,
                            AlphaCode = "EAKI",
                            BandSize = "1B",
                            MaxCulmen = 15.0,
                            MaxTail = 91.0,
                            MaxWing = 128.0,
                            MinCulmen = 13.9,
                            MinTail = 74.0,
                            MinWing = 106.0,
                            SpeciesName = "Eastern Kingbird"
                        },
                        new
                        {
                            SpeciesId = 20,
                            AlphaCode = "RCKI",
                            BandSize = "0A",
                            MaxCulmen = 7.5,
                            MaxTail = 51.0,
                            MaxWing = 63.0,
                            MinCulmen = 6.0,
                            MinTail = 38.0,
                            MinWing = 50.0,
                            SpeciesName = "Ruby-crowned Kinglet"
                        },
                        new
                        {
                            SpeciesId = 21,
                            AlphaCode = "GCKI",
                            BandSize = "0A",
                            MaxCulmen = 7.5,
                            MaxTail = 47.0,
                            MaxWing = 62.0,
                            MinCulmen = 6.25,
                            MinTail = 37.0,
                            MinWing = 49.0,
                            SpeciesName = "Golden-crowned Kinglet"
                        },
                        new
                        {
                            SpeciesId = 22,
                            AlphaCode = "RBNU",
                            BandSize = "0",
                            MaxCulmen = 14.1,
                            MaxTail = 39.0,
                            MaxWing = 73.0,
                            MinCulmen = 13.5,
                            MinTail = 33.0,
                            MinWing = 60.0,
                            SpeciesName = "Red-breasted Nuthatch"
                        },
                        new
                        {
                            SpeciesId = 23,
                            AlphaCode = "WBNU",
                            BandSize = "1B",
                            MaxCulmen = 23.0,
                            MaxTail = 52.0,
                            MaxWing = 96.0,
                            MinCulmen = 16.0,
                            MinTail = 39.0,
                            MinWing = 80.0,
                            SpeciesName = "White-breasted Nuthatch"
                        },
                        new
                        {
                            SpeciesId = 24,
                            AlphaCode = "BAOR",
                            BandSize = "1A",
                            MaxCulmen = 18.899999999999999,
                            MaxTail = 78.0,
                            MaxWing = 100.0,
                            MinCulmen = 15.800000000000001,
                            MinTail = 64.0,
                            MinWing = 83.0,
                            SpeciesName = "Baltimore Oriole"
                        },
                        new
                        {
                            SpeciesId = 25,
                            AlphaCode = "DOWO",
                            BandSize = "1B",
                            MaxCulmen = 18.800000000000001,
                            MaxTail = 72.0,
                            MaxWing = 115.0,
                            MinCulmen = 15.4,
                            MinTail = 48.0,
                            MinWing = 84.0,
                            SpeciesName = "Downy Woodpecker"
                        },
                        new
                        {
                            SpeciesId = 26,
                            AlphaCode = "OVEN",
                            BandSize = "1-0",
                            MaxCulmen = 13.9,
                            MaxTail = 57.0,
                            MaxWing = 81.0,
                            MinCulmen = 13.0,
                            MinTail = 48.0,
                            MinWing = 67.0,
                            SpeciesName = "Ovenbird"
                        },
                        new
                        {
                            SpeciesId = 27,
                            AlphaCode = "HAWO",
                            BandSize = "1A-2",
                            MaxCulmen = 33.5,
                            MaxTail = 90.0,
                            MaxWing = 138.0,
                            MinCulmen = 24.600000000000001,
                            MinTail = 59.0,
                            MinWing = 107.0,
                            SpeciesName = "Hairy Woodpecker"
                        },
                        new
                        {
                            SpeciesId = 28,
                            AlphaCode = "EAPH",
                            BandSize = "0-1",
                            MaxCulmen = 14.0,
                            MaxTail = 78.0,
                            MaxWing = 91.0,
                            MinCulmen = 13.0,
                            MinTail = 63.0,
                            MinWing = 76.0,
                            SpeciesName = "Eastern Phoebe"
                        },
                        new
                        {
                            SpeciesId = 29,
                            AlphaCode = "NOCA",
                            BandSize = "1A",
                            MaxCulmen = 18.699999999999999,
                            MaxTail = 127.0,
                            MaxWing = 105.0,
                            MinCulmen = 15.300000000000001,
                            MinTail = 86.0,
                            MinWing = 82.0,
                            SpeciesName = "Northern Cardinal"
                        },
                        new
                        {
                            SpeciesId = 30,
                            AlphaCode = "AMRE",
                            BandSize = "0A-0",
                            MaxCulmen = 11.0,
                            MaxTail = 58.0,
                            MaxWing = 69.0,
                            MinCulmen = 7.0,
                            MinTail = 52.0,
                            MinWing = 55.0,
                            SpeciesName = "American Redstart"
                        },
                        new
                        {
                            SpeciesId = 31,
                            AlphaCode = "AMRO",
                            BandSize = "2",
                            MaxCulmen = 23.0,
                            MaxTail = 112.0,
                            MaxWing = 145.0,
                            MinCulmen = 20.0,
                            MinTail = 85.0,
                            MinWing = 115.0,
                            SpeciesName = "American Robin"
                        },
                        new
                        {
                            SpeciesId = 32,
                            AlphaCode = "YBSA",
                            BandSize = "1B-1A",
                            MaxCulmen = 25.199999999999999,
                            MaxTail = 77.0,
                            MaxWing = 130.0,
                            MinCulmen = 19.300000000000001,
                            MinTail = 62.0,
                            MinWing = 110.0,
                            SpeciesName = "Yellow-bellied Sapsucker"
                        },
                        new
                        {
                            SpeciesId = 33,
                            AlphaCode = "PISI",
                            BandSize = "0",
                            MaxCulmen = 9.8000000000000007,
                            MaxTail = 50.0,
                            MaxWing = 77.0,
                            MinCulmen = 8.0999999999999996,
                            MinTail = 40.0,
                            MinWing = 66.0,
                            SpeciesName = "Pine Siskin"
                        },
                        new
                        {
                            SpeciesId = 34,
                            AlphaCode = "ATSP",
                            BandSize = "0",
                            MaxCulmen = 11.1,
                            MaxTail = 74.0,
                            MaxWing = 82.0,
                            MinCulmen = 7.7999999999999998,
                            MinTail = 60.0,
                            MinWing = 67.0,
                            SpeciesName = "American Tree Sparrow"
                        },
                        new
                        {
                            SpeciesId = 35,
                            AlphaCode = "LISP",
                            BandSize = "0",
                            MaxCulmen = 11.0,
                            MaxTail = 61.0,
                            MaxWing = 69.0,
                            MinCulmen = 7.0,
                            MinTail = 48.0,
                            MinWing = 54.0,
                            SpeciesName = "Lincoln Sparrow"
                        },
                        new
                        {
                            SpeciesId = 36,
                            AlphaCode = "SOSP",
                            BandSize = "1B",
                            MaxCulmen = 12.6,
                            MaxTail = 74.0,
                            MaxWing = 72.0,
                            MinCulmen = 10.300000000000001,
                            MinTail = 62.0,
                            MinWing = 59.0,
                            SpeciesName = "Song Sparrow"
                        },
                        new
                        {
                            SpeciesId = 37,
                            AlphaCode = "SWSP",
                            BandSize = "1",
                            MaxCulmen = 11.0,
                            MaxTail = 64.0,
                            MaxWing = 65.0,
                            MinCulmen = 7.0,
                            MinTail = 51.0,
                            MinWing = 52.0,
                            SpeciesName = "Swamp Sparrow"
                        },
                        new
                        {
                            SpeciesId = 38,
                            AlphaCode = "TRES",
                            BandSize = "1",
                            MaxCulmen = 7.0,
                            MaxTail = 57.0,
                            MaxWing = 125.0,
                            MinCulmen = 6.0,
                            MinTail = 49.0,
                            MinWing = 98.0,
                            SpeciesName = "Tree Swallow"
                        },
                        new
                        {
                            SpeciesId = 39,
                            AlphaCode = "SCTA",
                            BandSize = "1B",
                            MaxCulmen = 10.4,
                            MaxTail = 72.0,
                            MaxWing = 101.0,
                            MinCulmen = 9.9000000000000004,
                            MinTail = 62.0,
                            MinWing = 86.0,
                            SpeciesName = "Scarlet Tanager"
                        },
                        new
                        {
                            SpeciesId = 40,
                            AlphaCode = "BRTH",
                            BandSize = "2-3",
                            MaxCulmen = 28.800000000000001,
                            MaxTail = 141.0,
                            MaxWing = 117.0,
                            MinCulmen = 22.100000000000001,
                            MinTail = 111.0,
                            MinWing = 94.0,
                            SpeciesName = "Brown Thrasher"
                        },
                        new
                        {
                            SpeciesId = 41,
                            AlphaCode = "HETH",
                            BandSize = "1B",
                            MaxCulmen = 15.199999999999999,
                            MaxTail = 79.0,
                            MaxWing = 110.0,
                            MinCulmen = 13.0,
                            MinTail = 58.0,
                            MinWing = 78.0,
                            SpeciesName = "Hermit Thrush"
                        },
                        new
                        {
                            SpeciesId = 42,
                            AlphaCode = "SWTH",
                            BandSize = "1B",
                            MaxCulmen = 9.5,
                            MaxTail = 78.0,
                            MaxWing = 104.0,
                            MinCulmen = 8.0,
                            MinTail = 61.0,
                            MinWing = 87.0,
                            SpeciesName = "Swainson's Thrush"
                        },
                        new
                        {
                            SpeciesId = 43,
                            AlphaCode = "TUTI",
                            BandSize = "1B",
                            MaxCulmen = 13.0,
                            MaxTail = 79.0,
                            MaxWing = 86.0,
                            MinCulmen = 11.0,
                            MinTail = 64.0,
                            MinWing = 73.0,
                            SpeciesName = "Tufted Titmouse"
                        },
                        new
                        {
                            SpeciesId = 44,
                            AlphaCode = "EATO",
                            BandSize = "F-1A-2/M-2-1A",
                            MaxCulmen = 16.199999999999999,
                            MaxTail = 101.0,
                            MaxWing = 94.0,
                            MinCulmen = 12.9,
                            MinTail = 79.0,
                            MinWing = 72.0,
                            SpeciesName = "Eastern Towhee"
                        },
                        new
                        {
                            SpeciesId = 45,
                            AlphaCode = "VEER",
                            BandSize = "1B",
                            MaxCulmen = 14.6,
                            MaxTail = 79.0,
                            MaxWing = 106.0,
                            MinCulmen = 12.4,
                            MinTail = 62.0,
                            MinWing = 89.0,
                            SpeciesName = "Veery"
                        },
                        new
                        {
                            SpeciesId = 46,
                            AlphaCode = "REVI",
                            BandSize = "1",
                            MaxCulmen = 13.6,
                            MaxTail = 60.0,
                            MaxWing = 85.0,
                            MinCulmen = 11.6,
                            MinTail = 47.0,
                            MinWing = 72.0,
                            SpeciesName = "Red-eyed Vireo"
                        },
                        new
                        {
                            SpeciesId = 47,
                            AlphaCode = "COYE",
                            BandSize = "0-0A",
                            MaxCulmen = 15.0,
                            MaxTail = 58.0,
                            MaxWing = 58.0,
                            MinCulmen = 13.0,
                            MinTail = 43.0,
                            MinWing = 47.0,
                            SpeciesName = "Common Yellowthroat"
                        },
                        new
                        {
                            SpeciesId = 48,
                            AlphaCode = "YWAR",
                            BandSize = "0-0A",
                            MaxCulmen = 7.9000000000000004,
                            MaxTail = 50.0,
                            MaxWing = 68.0,
                            MinCulmen = 6.9000000000000004,
                            MinTail = 38.0,
                            MinWing = 55.0,
                            SpeciesName = "Yellow Warbler"
                        },
                        new
                        {
                            SpeciesId = 49,
                            AlphaCode = "YPWA",
                            BandSize = "0-0A",
                            MaxCulmen = 11.5,
                            MaxTail = 59.0,
                            MaxWing = 71.0,
                            MinCulmen = 10.5,
                            MinTail = 51.0,
                            MinWing = 61.0,
                            SpeciesName = "Palm Warbler"
                        },
                        new
                        {
                            SpeciesId = 50,
                            AlphaCode = "CEDW",
                            BandSize = "1B",
                            MaxCulmen = 8.0,
                            MaxTail = 61.0,
                            MaxWing = 100.0,
                            MinCulmen = 5.0,
                            MinTail = 50.0,
                            MinWing = 88.0,
                            SpeciesName = "Cedar Waxwing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
