// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200616181225_AddingAValue")]
    partial class AddingAValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlphaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BandSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxBillToTip")
                        .HasColumnType("float");

                    b.Property<double>("MaxCulmen")
                        .HasColumnType("float");

                    b.Property<double>("MaxTail")
                        .HasColumnType("float");

                    b.Property<double>("MaxWing")
                        .HasColumnType("float");

                    b.Property<double>("MinBillToTip")
                        .HasColumnType("float");

                    b.Property<double>("MinCulmen")
                        .HasColumnType("float");

                    b.Property<double>("MinTail")
                        .HasColumnType("float");

                    b.Property<double>("MinWing")
                        .HasColumnType("float");

                    b.Property<string>("SpeciesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
