// <auto-generated />
using System;
using BandTheBirdProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandTheBirdProj.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200622205002_Addedafewmodels")]
    partial class Addedafewmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandTheBirdProj.Models.Age", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Age");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "After Hatch Year"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hatch Year"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Local"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Second Year"
                        },
                        new
                        {
                            Id = 6,
                            Name = "After Second Year"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Third Year"
                        },
                        new
                        {
                            Id = 8,
                            Name = "After Third Year"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Not Attempted"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Indeterminable"
                        });
                });

            modelBuilder.Entity("BandTheBirdProj.Models.BandType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BandType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "N",
                            Name = "New Band"
                        },
                        new
                        {
                            Id = 2,
                            Code = "D",
                            Name = "Band Destroyed"
                        },
                        new
                        {
                            Id = 3,
                            Code = "L",
                            Name = "Band Lost"
                        },
                        new
                        {
                            Id = 4,
                            Code = "C",
                            Name = "Band Changed"
                        },
                        new
                        {
                            Id = 5,
                            Code = "A",
                            Name = "Band Added"
                        },
                        new
                        {
                            Id = 6,
                            Code = "R",
                            Name = "Recapture"
                        });
                });

            modelBuilder.Entity("BandTheBirdProj.Models.BandingData", b =>
                {
                    b.Property<int>("BirdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlphaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BandNumber")
                        .HasColumnType("float");

                    b.Property<string>("BandSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BandType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanderIntials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CaptureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaptureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NetNumber")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeciesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirdId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("SiteId");

                    b.ToTable("BandingData");
                });

            modelBuilder.Entity("BandTheBirdProj.Models.BiologicalData", b =>
                {
                    b.Property<int>("BioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BirdId")
                        .HasColumnType("int");

                    b.Property<int?>("BodyMolt")
                        .HasColumnType("int");

                    b.Property<int?>("BroodPatch")
                        .HasColumnType("int");

                    b.Property<int?>("CloacalProtuberance")
                        .HasColumnType("int");

                    b.Property<double>("ExposedCulmen")
                        .HasColumnType("float");

                    b.Property<int?>("Fat")
                        .HasColumnType("int");

                    b.Property<string>("FlightFeatherMolt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlightFeatherWear")
                        .HasColumnType("int");

                    b.Property<string>("HowAged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowSexed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Skull")
                        .HasColumnType("int");

                    b.Property<double>("TailLength")
                        .HasColumnType("float");

                    b.Property<double?>("Tarsus")
                        .HasColumnType("float");

                    b.Property<double>("WingChord")
                        .HasColumnType("float");

                    b.HasKey("BioId");

                    b.HasIndex("BirdId");

                    b.ToTable("BiologicalData");
                });

            modelBuilder.Entity("BandTheBirdProj.Models.Environmental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CloseTemp")
                        .HasColumnType("float");

                    b.Property<string>("CloseTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudCover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OpenTemp")
                        .HasColumnType("float");

                    b.Property<string>("OpenTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precipitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResearchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Environmental");
                });

            modelBuilder.Entity("BandTheBirdProj.Models.HowAgeSex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HowAgeSex");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "S",
                            Name = "Skull"
                        },
                        new
                        {
                            Id = 2,
                            Code = "C",
                            Name = "Cloacal Prot."
                        },
                        new
                        {
                            Id = 3,
                            Code = "B",
                            Name = "Brood Patch"
                        },
                        new
                        {
                            Id = 4,
                            Code = "J",
                            Name = "Juvenile Body Plumage"
                        },
                        new
                        {
                            Id = 5,
                            Code = "L",
                            Name = "Molt Limit"
                        },
                        new
                        {
                            Id = 6,
                            Code = "P",
                            Name = "Plumage"
                        },
                        new
                        {
                            Id = 7,
                            Code = "M",
                            Name = "Molt"
                        },
                        new
                        {
                            Id = 8,
                            Code = "F",
                            Name = "Feather Wear"
                        },
                        new
                        {
                            Id = 9,
                            Code = "I",
                            Name = "Mouth/Bill"
                        },
                        new
                        {
                            Id = 10,
                            Code = "E",
                            Name = "Eye Color"
                        },
                        new
                        {
                            Id = 11,
                            Code = "W",
                            Name = "Wing Length"
                        },
                        new
                        {
                            Id = 12,
                            Code = "T",
                            Name = "Tail Length"
                        },
                        new
                        {
                            Id = 13,
                            Code = "O",
                            Name = "Other(Note)"
                        });
                });

            modelBuilder.Entity("BandTheBirdProj.Models.ResearchSite", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("SiteCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteStreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteZip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId");

                    b.ToTable("ResearchSite");
                });

            modelBuilder.Entity("BandTheBirdProj.Models.Researcher", b =>
                {
                    b.Property<int>("ResearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchSiteAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchSiteCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchSiteState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResearchSiteZip")
                        .HasColumnType("int");

                    b.HasKey("ResearchId");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Researcher");
                });

            modelBuilder.Entity("BandTheBirdProj.Models.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sex");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "M",
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Code = "F",
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Code = "U",
                            Name = "Undetermined"
                        },
                        new
                        {
                            Id = 4,
                            Code = "X",
                            Name = "Not Attempted"
                        });
                });

            modelBuilder.Entity("BandTheBirdProj.Models.Species", b =>
                {
                    b.Property<int>("speciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alphaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bandSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("maxCulmen")
                        .HasColumnType("real");

                    b.Property<int>("maxTail")
                        .HasColumnType("int");

                    b.Property<int>("maxWing")
                        .HasColumnType("int");

                    b.Property<float>("minCulmen")
                        .HasColumnType("real");

                    b.Property<int>("minTail")
                        .HasColumnType("int");

                    b.Property<int>("minWing")
                        .HasColumnType("int");

                    b.Property<string>("speciesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("speciesId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "b2a8e385-182c-4e47-aa4f-047360d8421d",
                            ConcurrencyStamp = "bd0cba80-dc75-44e0-9ec6-40c442032bc6",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "62357c39-c45c-41cf-87b5-8722ec8812a6",
                            ConcurrencyStamp = "e4a0411c-d902-4236-a0e2-d062d83de027",
                            Name = "Researcher",
                            NormalizedName = "Researcher"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BandTheBirdProj.Models.BandingData", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.HasOne("BandTheBirdProj.Models.ResearchSite", "ResearchSite")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BandTheBirdProj.Models.BiologicalData", b =>
                {
                    b.HasOne("BandTheBirdProj.Models.BandingData", "BandingData")
                        .WithMany()
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BandTheBirdProj.Models.Environmental", b =>
                {
                    b.HasOne("BandTheBirdProj.Models.ResearchSite", "ResearchSite")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BandTheBirdProj.Models.Researcher", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
